#! /usr/bin/env python

# Copyright (C) 2014 Sony Mobile Communications AB.
# All rights, including trade secret rights, reserved.

if __name__ == '__main__':
    import runners
    runners.all_restart()
