#! /usr/bin/python2

# Copyright (C) 2013 Sony Mobile Communications AB.
# All rights, including trade secret rights, reserved.

import os
import sys

if __name__ == '__main__':
    import runners
    runners.all_remote_share_basic()
