#! /usr/bin/python2

# Copyright (C) 2015 Sony Mobile Communications AB.
# All rights, including trade secret rights, reserved.

import os
import sys
import psutil
import json

import ave.cmd
import ave.config

PID_PATH = '/var/tmp/ave-broker.pid'

def patch_config():
    user = '/etc/ave/user'
    if os.path.exists(user):
        try:
            f = open(user, 'r')
            j = json.load(f)
            if 'uid' not in j:
                uid = ave.pwd.getpwnam_uid(j['name'])
                j['uid'] = uid
                f = open(user, 'w')
                f.write(json.dumps(j, indent=4))
        except Exception, e:
            raise Exception('could not get current uid %s' % e)

def is_running():
    if not os.path.exists(PID_PATH):
        return False
    pid = int(open(PID_PATH).read())
    try:
        return True
    except psutil.NoSuchProcess:
        return False

def main():
    if len(sys.argv) > 1:
        if sys.argv[1] in ['configure']:

            patch_config()

            # start or restart the service
            if is_running():
                ave.cmd.run(['/usr/bin/ave-broker', '--restart'])
            else:
                ave.cmd.run(['/usr/bin/ave-broker', '--start', '--force'])

    return 0

if __name__ == '__main__':
    sys.exit(main())
