#! /usr/bin/python2

# Copyright (C) 2014 Sony Mobile Communications Inc.
# All rights, including trade secret rights, reserved.

import os
import sys
import vcsjob
import runners

if __name__ == '__main__':
    result = runners.all_async_rpc()
    if result == True:
        sys.exit(vcsjob.OK)
    sys.exit(vcsjob.FAILURES)
