#! /usr/bin/python2

# Copyright (C) 2013-2014 Sony Mobile Communications Inc.
# All rights, including trade secret rights, reserved.

import sys

if __name__ == '__main__':
    import runners
    result = runners.all_daemon()

    import vcsjob
    if not result:
        sys.exit(vcsjob.FAILURES)
    sys.exit(vcsjob.OK)
