#! /usr/bin/python2

# Copyright (C) 2013 Sony Mobile Communications AB.
# All rights, including trade secret rights, reserved.

import os
import sys

try:
    import coverage
except:
    print(
        'ERROR: module "coverage" not found. please install the package '
        '"python-coverage". (The exact name depends on the distribution '
        'you use.)'
    )
    sys.exit(1)

if __name__ == '__main__':
    # make sure the test module can find its imports and the local libfdtx.so
    path = os.path.dirname(os.path.dirname(__file__))
    path = os.path.join(path, 'src')
    sys.path.insert(0, path)
    so_path = os.path.join(path, 'libfdtx', 'libfdtx.so')

    coverage.use_cache(False)
    coverage.start()

    import ave.network.fdtx
    import runners
    runners.all_fdtx(so_path)

    coverage.stop()
    coverage.report([ave.network.fdtx], file=None)
    sys.exit(0)

