#! /usr/bin/python2

# Copyright (C) 2014 Sony Mobile Communications AB.
# All rights, including trade secret rights, reserved.

import sys
import runners

if __name__ == '__main__':
    sys.exit(runners.all_process())
