#! /usr/bin/python2

import os
import sys

if __name__ == '__main__':
    # make sure the test module can find its imports
    path = os.path.dirname(os.path.dirname(__file__))
    sources = os.path.join(path, 'src')
    sys.path.insert(0, sources)

    import runners
    runners.all_duration()